
services:
  backend:
    container_name: backend
    build: ./backend/tarotMilkTea/tarotback
    expose:
      - 8000
    env_file:
      - ./backend/tarotMilkTea/tarotback/.env
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
  frontend:
    container_name: frontend
    build: ./frontend/tarotmilktea
    expose:
      - 3000
    env_file:
      - ./frontend/tarotmilktea/.env
    volumes:
      - frontend:/var/www/frontend
    depends_on:
      - backend
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    depends_on:
      - frontend

volumes:
  static:
    external: false
  media:
    external: true
  frontend:
    external: false
