# Generated by Django 4.1.13 on 2024-06-10 03:27

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('provider', models.CharField(default='email', max_length=50)),
            ],
        ),
    ]
