# Generated by Django 4.1.13 on 2024-06-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='provider',
            field=models.CharField(max_length=50),
        ),
    ]
