# Generated by Django 4.1.13 on 2024-05-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.IntegerField(unique=True)),
                ('card_name', models.CharField(max_length=100, unique=True)),
                ('card_means', models.TextField(default='[]')),
                ('card_url', models.URLField(max_length=255)),
            ],
        ),
    ]
