# Generated by Django 5.0.6 on 2024-06-15 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarotcard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarotResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.TextField()),
                ('past', models.TextField()),
                ('present', models.TextField()),
                ('future', models.TextField()),
                ('advice', models.TextField()),
                ('conclusion', models.TextField()),
                ('selected_cards', models.JSONField()),
                ('selected_cards_name', models.JSONField()),
                ('subject', models.CharField(max_length=255)),
                ('consulValue', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
