# Generated by Django 4.1.13 on 2024-05-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarotcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotcard',
            name='card_url',
            field=models.CharField(max_length=255),
        ),
    ]
