# Generated by Django 4.1.13 on 2024-06-01 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarotcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarotcardmeaning',
            name='card_num',
        ),
    ]
