# Generated by Django 4.1.13 on 2024-06-02 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarotcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarotcardmeaning',
            name='card_mean_reverse',
        ),
        migrations.CreateModel(
            name='TarotCardReverseMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_reverse_mean', models.CharField(max_length=255)),
                ('tarotcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarotcards.tarotcard')),
            ],
        ),
    ]
