# Generated by Django 4.1.13 on 2024-06-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarotcards', '0002_remove_tarotcardmeaning_card_mean_reverse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarotPictureMean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_mean', models.CharField(max_length=255)),
                ('tarotcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarotcards.tarotcard')),
            ],
        ),
        migrations.CreateModel(
            name='TarotNumerologyMean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerology_mean', models.CharField(max_length=255)),
                ('tarotcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarotcards.tarotcard')),
            ],
        ),
        migrations.CreateModel(
            name='TarotMeanExplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.TextField()),
                ('tarotcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarotcards.tarotcard')),
            ],
        ),
    ]
